version: '3.4'

services:

  restserver:
    image: ${RESTSERVER_IMAGE_NAME}
    container_name: ${EX2_CONTAINER_NAME}
    ports:
      - 80:9090
    networks:
      - local


networks:
  local:
    name: ${EX2_NETWORK_NAME}

