version: '3.4'

services:

  ex3_1:
    image: ${RESTSERVER_IMAGE_NAME}
    container_name: ex3_1
    ports:
      - 9090:9090
    networks:
      local:
        ipv4_address: 172.28.5.0

  ex3_2:
    image: ${RESTSERVER_IMAGE_NAME}
    container_name: ex3_2
    ports:
      - 9091:9090
    networks:
      local:
        ipv4_address: 172.28.5.1

networks:
  local:
    driver: bridge
    name: ${EX3_NETWORK_NAME}
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
      

