version: '3.4'

services:

  restserver:
    image: ${RESTSERVER_IMAGE_NAME}
    container_name: restserver
    ports:
      - 80:9090
    networks:
      - local

networks:
  local:
    driver: bridge
    name: ${REST_NETWORK_NAME}


