version: '3.4'

services:

  restserver:
    image: ${RESTSERVER_IMAGE_NAME}
    container_name: restserver
    ports:
      - 80:9090
    networks:
      - network1

networks:
  network1:
    driver: bridge
    name: learn-docker_network1

