version: '3.4'

services:

  gha:
    image: ${IMAGE_NAME}
    container_name: gha
    ports:
      - 80:9090
    networks:
      - network1

networks:
  network1:
    driver: bridge
    name: learn-compose_network1

