name: "ci-for-docker"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out code
        uses: actions/checkout@v2

      - name: Build image
        run: ./scripts/gha.sh build